[package]
name = "tutor-nodb"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "basic-server"

# [[bin]]
# name = "tutor-service"

[dependencies]
actix-web = "4.9.0"
## The async runtime for Actix. Rust requires an external runtime engine for executing async code.
actix-rt = "2.10.0"
